export const RAW_TRIGGER_INTERVAL_MINUTES = 1;
export const SHARD_COUNT = 10;
export const MAX_TINYBIRD_INGESTION_CALLS_PER_MINUTE = 5;
export const MAX_TABLES_PER_RUN = MAX_TINYBIRD_INGESTION_CALLS_PER_MINUTE;
export const RAW_GENERATION_COVERAGE_MINUTES = (
  RAW_TRIGGER_INTERVAL_MINUTES * SHARD_COUNT
);
